post_title = "About this personal website and CV solution"
subtitle = "How I came up with it and how I did (am doing) it"
post_author = "Andras Denes"
date = "2023.03.07."
image = "https://i.imgur.com/Ij9tljw.png"
post_body = """
sample post body
"""