[[experiences]]
title = "work experience"

  [[experiences.job]]
  job_title = "Software Engineer"
  company.name = "Evosoft"
  company.url = "https://evosoft.hu"
  image = "https://dreamjo.bs/uploads/evosoft-1/dc84ef3e41a0.jpg"
  image_alt = "evo"
  from = 2021.01
  to = ""
  description = """
  I worked on a **complex engineering software**, and up to this day I still work on some of its components.
  Since January 2022 our agile team was assigned a new project and we have been working on that ever since. We are
  developing a solution to make certain data more accessible to all the engineering software that we can support.
  Our **REST** interface supplies all the required data to customers, in the exact format they require.

  One thing I'm responsible for is product configuration. This sounds easy enough but actually it is quite challenging.
  Think about buying a car. Some parameters will inevitably have an effect on other parameters - but how do the 
  affected parameters relate to the previous ones? Or perhaps completely different options should be selected?

  I also actively take part in the data-management solution. I develop **REST** endpoints, write unit and integration tests, review code and
  fix the occasional error - be it in the data access layer or as simple as the **DTO** definition.

  Recently I also became responsible for our **CI system**, that is just a fancy name for a bunch of **Jenkins** jobs.

  I'm lazy, so I have automated some of my work at Evosoft - using **python and C#** - to ease my life and others' and naturally, 
  to produce consistent results. Probably these automations are what I'm the most proud of since **I saved a bunch of effort to developers,
  and probably a lot of money for the company**.

  Finally, to top everything else, in March, 2021 me and 2 colleagues **took part in a hackathon in Szeged, Hungary and our app idea got such 
  a decent amount of recognition that Evosoft and the city of Szeged decided to actually realize the App**. This project makes us well versed in 
  **Blazor**. 
  """
  tags = [ "C#", ".NET", "Python", "Automation", "Javascript", "ASP.NET", ".NETMVC", "Blazor", "REST" ]

  [[experiences.job]]
  job_title = "Python Developer"
  company.name = "University of Szeged"
  company.url = "https://www.inf.u-szeged.hu/rgai"
  image = ""
  image_alt = "szte"
  from = 2020.09
  to = 2021.07
  description = """
  The job I took at my university required me to develop a deep understanding of **python** and more importantly **Django**.
  Essentially, I was working on a website, that opened up a convenient user interface on top of an AI-driven application.
  The project's focus was to optimally match possible partner companies, filter for competitors, analyze market competition or perhaps determine if expanding bussiness to a given target country is worth it.
  This was/is actually an EU-financed software solution that should benefit all companies in the world - European or otherwise.
  I got familiar with **databases (SQL and DocumentDBs, mostly)**, I learnt how to use **Bootstrap** well, I got to know the **jinja2** templating engine,
  I became quite confident with **Django**, its migrations system (and fixing migration issues when things go sideways), I got to know **javascript, jquery, chart.js** and a whole bunch of other js package. 
  Data processing with **pandas and numpy** is something I got quite good at. The occasional **nginx config** fix was just a lovely cherry on top of everything.  
  """
  tags=["python", "django", "pandas", "numpy", "SQL", "noSQL","database", "DB", "Bootstrap", "Jinja2", "HTML", "CSS", "nginx", "web", "REST"]

  [[experiences.job]]
  job_title = "Software Engineer"
  company.name = "Gerhardt Informatics"
  company.url = "https://gerhardt.io"
  image = ""
  image_alt = "gi"
  from = 2019.06
  to = 2021.01
  description = """
  I started working at Gerhardt Informatics as an intern in June, 2019. After finishing my internship, 
  I was offered a student position. I mostly worked on 2 projects. One I would Consider an **RPA** project as it was  a chatbot
  for our developers, which we alter wanted to integrate into our communications platform. Essentially, this chatbot would have taken care of
  administrative tasks, thus sparing time for developers. The skills of the cahtbot **use Google APIs** llike Calendar and Drive/Sheets, **Git** and **YouTrack**.
  The other project was our own internal communications server. I had a "blueprint" here, but to integrate the chatbot, I needed additional functionality, which I coded myself.
  I also did some **mentoring**. Gradually, new colleagues were introduced to the chatbot development, so that I could keep working on the server-side of things,
  to keep the platform ready for the newest bot versions and skills.
  I have also been **automating deployment processes** for the CMS of the company website, and our **custom identity provider, which was based on Keycloak.**
  For these deployment solutions, I used **jupyter** notebooks, **python** and I also had to transcribe **ansible playbooks**, so I have a rough understanding of that as well.
  Last but not least, when I left I was actively working on the **authentication system** of a ridesharing platform, using **Keycloak** and **PHP**.
  
  """
  tags=["python", "Linux", "shell", "mentoring", "jupyter", "web", "API", "nginx", "Go", "caddy", "Keycloak", "SSO", "ansible"]